sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t indietyp/hawthorne .

deploy:
  provider: script
  script: bash cli/utils/travis.sh
  on:
    branch: master
