sudo: required

matrix:
  include:
  - name: "Docker Image Build"
    language: minimal
    script:
      - docker build -t indietyp/hawthorne .
    deploy:
      skip_cleanup: true
      provider: script
      script: bash cli/utils/travis.sh
      on:
        branch:
          - master
          - dev

  - name: "centOS Functionality Test"
    language: minimal
    script:
      - docker network create net-db
      - docker run --name db --network net-db -e MYSQL_ROOT_PASSWORD=testing -d mariadb
      - docker run -itd --name centos --network net-db centos
      - docker cp . centos:/hawthorne
      - docker exec -t centos sh /hawthorne/cli/install.sh --path /hawthorne --local --headless --domain localhost --steam $STEAMAPI --admin $STEAMADMIN --database root:testing@db:3306/hawthorne

  - name: "Ubuntu Functionality Test"
    language: minimal
    script:
      - docker network create net-db
      - docker run --name db --network net-db -e MYSQL_ROOT_PASSWORD=testing -d mariadb
      - docker run -itd --name ubuntu --network net-db ubuntu
      - docker cp . ubuntu:/hawthorne
      - docker exec -t ubuntu sh /hawthorne/cli/install.sh --path /hawthorne --local --headless --domain localhost --steam $STEAMAPI --admin $STEAMADMIN --database root:testing@db:3306/hawthorne

  - name: "Debian Functionality Test"
    language: minimal
    script:
      - docker network create net-db
      - docker run --name db --network net-db -e MYSQL_ROOT_PASSWORD=testing -d mariadb
      - docker run -itd --name debian --network net-db debian
      - docker cp . debian:/hawthorne
      - docker exec -t debian sh /hawthorne/cli/install.sh --path /hawthorne --local --headless --domain localhost --steam $STEAMAPI --admin $STEAMADMIN --database root:testing@db:3306/hawthorne

  - name: "Ubuntu Reinstallation Test"
    language: minimal
    script:
      - docker network create net-db
      - docker run --name db --network net-db -e MYSQL_ROOT_PASSWORD=testing -d mariadb
      - docker run -itd --name ubuntu --network net-db ubuntu
      - docker cp . ubuntu:/hawthorne
      - docker exec -t ubuntu sh /hawthorne/cli/install.sh --path /hawthorne --local --headless --domain localhost --steam $STEAMAPI --admin $STEAMADMIN --database root:testing@db:3306/hawthorne
      - docker exec -t ubuntu sh /hawthorne/cli/install.sh --path /hawthorne --local --headless --domain localhost --steam $STEAMAPI --admin $STEAMADMIN --database root:testing@db:3306/hawthorne

services:
  - docker

branches:
  except:
  - interface

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

# docker unit testing APIv2
