sudo: required

branches:
  except:
  - interface

language: python
python:
  - "3.6"

services:
  - docker

script:
  - docker build -t indietyp/hawthorne .

deploy:
  skip_cleanup: true
  provider: script
  script: bash cli/utils/travis.sh
  on:
    tags: true
    branch:
      - master
      - dev
