sudo: required

language: python

services:
  - docker

install:
  - docker build -t indietyp/hawthorne .

deploy:
  skip_cleanup: true
  provider: script
  script: bash cli/utils/travis.sh
  on:
    branch: master
