sudo: required

branches:
  except:
  - dev
  - interface

language: python

services:
  - docker

script:
  - docker build -t indietyp/hawthorne .

deploy:
  skip_cleanup: true
  provider: script
  script: bash cli/utils/travis.sh
  on:
    branch: master
